version: '3.4'
services:
  api:
    build: ./news.api
    ports:
      - "3001:3001"
    volumes:
      - ./news.api/src:/app/src
      - ./news.api/package.json:/app/package.json
      - ./news.api/package-lock.json:/app/package-lock.json
    environment:
      - PORT=3001
  front:
    build: ./news.front
    ports:
      - "8080:8080"
#       - DATABASE_URL=mysql://news:news@mysql:3306/news

#   mysql:
#     image: mysql:8.0.26
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_ROOT_PASSWORD=pass
#       - MYSQL_DATABASE=news
#       - MYSQL_USER=news
#       - MYSQL_PASSWORD=pass
#     volumes:
#       - mysql:/var/lib/mysql

# volumes:
#   mysql: